image: golang:latest

stages:
  - validate
  - release

validate:
  stage: validate
  script:
    - test -z $(gofmt -l -w -s .) # Make sure no formatting is needed

release:
  stage: release
  only:
    - tags
  except:
    - branches
  script:
    - curl -sL https://git.io/goreleaser | bash
