image: goreleaser/goreleaser:latest

stages:
  - validate
  - release

validate:
  stage: validate
  script:
    - test -z $(gofmt -l -w -s .) # Make sure no formatting is needed
    - test -z $(go mod tidy)      # Make sure there's no unused packages

release:
  stage: release
  only: tags
  script:
    - goreleaser
