project_name: glen
env:
  - CGO_ENABLED=0
  - GO111MODULE=on
before:
  hooks:
    - go mod download
archives:
  - id: glen
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
brew:
  name: glen
  description: "A CLI to export GitLab project and group variables"
  skip_upload: auto
  github:
    owner: lingrino
    name: homebrew-tap
  commit_author:
    name: Sean Lingren
    email: sean@lingrino.com
  folder: Formula
  dependencies:
    - git
  test: |
    system "#{bin}/glen version"
